// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIgzv6AuGQTlXIxWNiCSdFICzaszHnyNU',
    appId: '1:453876412282:web:3f41e7fceca28a2a0bb0c3',
    messagingSenderId: '453876412282',
    projectId: 'versionadoaplicacion',
    authDomain: 'versionadoaplicacion.firebaseapp.com',
    storageBucket: 'versionadoaplicacion.firebasestorage.app',
    measurementId: 'G-WZ1FBNG5RV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAijriwrEhTLj7Eu2bltB7rE6IJldrnjPk',
    appId: '1:453876412282:android:7ab23e78aa7c7e410bb0c3',
    messagingSenderId: '453876412282',
    projectId: 'versionadoaplicacion',
    storageBucket: 'versionadoaplicacion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpHjJRLEM0lHzluyY3cwL9P52NxIZ_9RA',
    appId: '1:453876412282:ios:66f8c122489af6ec0bb0c3',
    messagingSenderId: '453876412282',
    projectId: 'versionadoaplicacion',
    storageBucket: 'versionadoaplicacion.firebasestorage.app',
    iosBundleId: 'com.example.electiva2026',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpHjJRLEM0lHzluyY3cwL9P52NxIZ_9RA',
    appId: '1:453876412282:ios:66f8c122489af6ec0bb0c3',
    messagingSenderId: '453876412282',
    projectId: 'versionadoaplicacion',
    storageBucket: 'versionadoaplicacion.firebasestorage.app',
    iosBundleId: 'com.example.electiva2026',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIgzv6AuGQTlXIxWNiCSdFICzaszHnyNU',
    appId: '1:453876412282:web:6d56afa5d86f57440bb0c3',
    messagingSenderId: '453876412282',
    projectId: 'versionadoaplicacion',
    authDomain: 'versionadoaplicacion.firebaseapp.com',
    storageBucket: 'versionadoaplicacion.firebasestorage.app',
    measurementId: 'G-VF51R9J27D',
  );
}